/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffe083",
        "tertiary-fixed-dim": "#eec200",
        "inverse-primary": "#d0bcff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "on-error": "#ffffff",
        "secondary": "#006b5f",
        "primary-fixed": "#e9ddff",
        "tertiary": "#735c00",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#6d3bd7",
        "primary-container": "#8455ef",
        "on-primary-fixed": "#23005c",
        "tertiary-container": "#cea700",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#231b00",
        "background": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed-variant": "#005047",
        "on-primary-fixed-variant": "#5516be",
        "secondary-fixed": "#62fae3",
        "on-tertiary": "#ffffff",
        "outline": "#7b7486",
        "on-surface-variant": "#494454",
        "secondary-container": "#62fae3",
        "on-tertiary-container": "#4e3e00",
        "surface": "#f9f9f9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "primary": "#6b38d4",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e2e2e2",
        "outline-variant": "#cbc3d7",
        "surface-container-low": "#f3f3f4",
        "on-primary-container": "#fffbff",
        "surface-variant": "#e2e2e2",
        "surface-container": "#eeeeee",
        "on-surface": "#1a1c1c",
        "on-tertiary-fixed-variant": "#574500",
        "on-primary": "#ffffff",
        "surface-dim": "#dadada",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#3cddc7",
        "on-secondary-container": "#007165",
        "on-secondary-fixed": "#00201c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        sm: "16px",
        gutter: "24px",
        md: "24px",
        xs: "8px",
        margin: "32px",
        xl: "64px",
        lg: "40px",
      },
      fontFamily: {
        "label-bold": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-bold": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "1", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.5", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "display-bold": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "900" },
        ],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
